import { SiteNav } from '@/components/SiteNav';
import { supplyImages } from '@/lib/demo-data';

const deliveries = [
  { school: 'Henderson North School', date: '14 Aug 2026', items: '42 backpacks and 80 pencil cases', image: supplyImages.classroom },
  { school: 'Ōtāhuhu Primary School', date: '02 Aug 2026', items: '210 exercise books and 300 pencils', image: supplyImages.pencils },
  { school: 'Mt Roskill Grammar', date: '22 Jul 2026', items: '16 calculators and 45 binders', image: supplyImages.stationery },
];

export default function ImpactPage() {
  return <main className="min-h-screen bg-canvas"><SiteNav /><section className="mx-auto max-w-7xl px-6 py-12 sm:py-16"><div className="mb-12 max-w-3xl"><p className="mb-4 text-sm font-semibold uppercase tracking-wider text-primary">Our impact</p><h1 className="text-5xl leading-tight sm:text-7xl">Every pledge should come back with proof.</h1><p className="mt-5 text-xl text-ink/70">We publish what was requested, what was delivered, and when each school confirmed receipt.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg bg-primary p-6 text-white"><p className="text-5xl font-extrabold">1,248</p><p className="mt-2 text-white/80">items delivered</p></div><div className="rounded-lg bg-secondary p-6 text-white"><p className="text-5xl font-extrabold">18</p><p className="mt-2 text-white/80">Auckland schools</p></div><div className="rounded-lg bg-accent p-6 text-ink"><p className="text-5xl font-extrabold">$0</p><p className="mt-2 text-ink/70">cash processed</p></div><div className="rounded-lg bg-ink p-6 text-white"><p className="text-5xl font-extrabold">100%</p><p className="mt-2 text-white/70">delivery confirmation</p></div></div><div className="mt-16"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-secondary">Delivery log</p><h2 className="mt-2 text-4xl">Recently completed</h2></div><span className="text-sm text-ink/60">Updated weekly</span></div><div className="grid gap-6 md:grid-cols-3">{deliveries.map((delivery) => <article key={delivery.school} className="overflow-hidden rounded-lg bg-muted"><img src={delivery.image} alt="School supplies prepared for delivery" className="h-48 w-full object-cover" /><div className="p-6"><p className="text-sm font-semibold text-primary">{delivery.date}</p><h3 className="mt-2 text-2xl">{delivery.school}</h3><p className="mt-3 text-ink/70">{delivery.items}</p><span className="mt-5 inline-block rounded-md bg-secondary px-3 py-2 text-sm font-semibold text-white">Confirmed delivered</span></div></article>)}</div></div></section></main>;
}
